language: go
sudo: false
notifications:
  email: false
jobs:
  include:
  - go: 1.11.x
    stage: deploy
    go_import_path: github.com/wzshiming/pic2ascii
    install: skip
    script: skip
    before_deploy:
    - BASENAME=pic2ascii ./build_all.bash
    deploy:
      provider: releases
      api_key: $CI_TOKEN
      file_glob: true
      file: release/*
      skip_cleanup: true
      on:
        repo: wzshiming/pic2ascii
        branch: master
        tags: true
